compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
mixed_precision: 'fp16'
use_cpu: false
gpu_ids: '0'
rdzv_backend: 'static'
same_network: true
machine_rank: 0
num_processes: 1
num_machines: 1
main_training_function: main
